### ISSUE TITLE
Encoding of captured data is not correct

### ISSUE THREAD

**Issue by aduffeck** [openSUSE/cheetah#15]
Look at this example:

```
irb(main):020:0> `lzma -cd #{compressed_file_name}`.encoding.name
=> "UTF-8"

irb(main):021:0> Cheetah.run('lzma', '-cd', compressed_file_name, :stdout => :capture).encoding.name
=> "US-ASCII"
irb(main):022:0> Cheetah.run('lzma', '-cd', compressed_file_name, :stdout => :capture).valid_encoding?
=> false
```

I don't know how `` determines the encoding but it would be great if cheetah could also "just work" or at least allow for specifying the encoding.

**Comment by jreidinger** [comment]
now it use by default UTF-8 with newer ruby. 

irb(main):003:0> Cheetah.run('ls', stdout: :capture).encoding.name
=> "UTF-8"

Can you provide example of not working case?

**Comment by jreidinger** [comment]
@aduffeck ping

**Comment by aduffeck** [comment]
@jreidinger it seems to work for me now on newer , we can close this from my pov

**Comment by jreidinger** [comment]
thanks, so lets close
