### ISSUE TITLE
Optionally do not raise Cheetah::ExecutionFailed when exit status in non-zero

### ISSUE THREAD

**Issue by lslezak** [openSUSE/cheetah#16]
Some commands indicate result via exit status, e.g. "grep", "pgrep"... In this case non-zero value does not mean that the command failed and raising the exception makes testing of the result more difficult.

In my case I'm running "pgrep -c -f <command>" which according to the manual page returns:
       0      One or more processes matched the criteria.
       1      No processes matched.
       2      Syntax error in the command line.
       3      Fatal error: out of memory etc.

So in this case exit status 2 or greater mean failure, value 1 is a valid (expected) value.

It would be nice to have a config option for disabling Cheetah::ExecutionFailed exception and to manually check the exit value whether there was a problem or not.

**Comment by jreidinger** [comment]
fixed by #31
