### ISSUE TITLE
Add support for passing environment variables

### ISSUE THREAD

**Issue by dmajda** [openSUSE/cheetah#17]
Calls like `system "LC_ALL='en_US.UTF-8' foo"` can't be ported to Cheetah ATM.

One way to implement this is adding the `:env` option and emulate `Process.spawn` semantics:

    env: hash
      name => val : set the environment variable
      name => nil : unset the environment variable

**Comment by jreidinger** [comment]
fixed by https://github.com/openSUSE/cheetah/pull/32
