### ISSUE TITLE
Add ability to change command's working directory

### ISSUE THREAD

**Issue by dmajda** [openSUSE/cheetah#18]

**Comment by jreidinger** [comment]
why is
```
Dir.chdir("/bla") do
  Cheetah.run ...
end
```
not sufficient?

**Comment by dmajda** [comment]
I think it is sufficient, not sure why I originally filed this issue (it probably wasn’t sufficient for someone who bugged me enough to file it). Feel free to close.

**Comment by jreidinger** [comment]
@dmajda thanks. I will add note to documentation about that usage and then close it.

**Comment by jreidinger** [comment]
documented in #31
